library(shinydashboard)
library(shiny)
library(tableHTML)
  home <- fluidPage(
    fluidRow(
      box (h2(" DataBot"),
          status = "primary",
          solidHeader = F,
          collapsible = F,
          width = 12,
          includeHTML("index.html")
      )
      
    ),
    fluidRow(
      tags$style(make_css(list('.box', 
                               c('font-size', 'font-family', 'color'), 
                               c('14px', 'Arial Black', '1e90ff')))),
      box(
        h2("DataBot: A Machine Learning-Enabled Data
        Analytics Service for Equity Trading Applications
          "),
          status = "primary",
          solidHeader = F,
          collapsible = F,
          width = 6,
          img(src="66.png")
          
      ),
      box(
                  "DataBot is a Machine Learning-Enabled Data Analytics Service for

                   Equity Trading Applications (ETAs). It is also a middleware service that can generically 

                   be plugged into ETA(s) and access the data generated by the application.
          ",
          status = "primary",
          solidHeader = F,
          collapsible = F,
          width = 6,
          img(src = "ohlc.png")
      )
    ),
    fluidRow(
      box(
        h2("Visualisations and Predictive Analysis
           "),
          "Predictive analysis and visualisations for Stock data provided by ETAs including different prediction types.
          ",
          status = "primary",
          solidHeader = F,
          collapsible = F,
          width = 6,
         img(src = "333.png") 
      ),
      box(title = "Predictive Analysis Using Stock Data to help investors have knowledge on where to invest their money.
          ",
          status = "primary",
          solidHeader = F,
          collapsible = F,
          width = 6,
          img(src="88.jpg")
          
      )
      ),
    fluidRow(
      box(title = " 
          
          ",
          status = "primary",
          solidHeader = F,
          collapsible = F,
          width = 12,
          sliderInput("slider", label = "", min = 100, max = 300, value = 200),
          uiOutput('logo')
      )
          
      )
    )
    
