library(shiny)
library(shinydashboard)
library(plotly)
library(ggplot2)
library(DT)
library(RMySQL)

source("header.R")
source("sidebar.R")
source("body.R")
source("createAccount.R")
source("renderVisualisation.R")
source("analysisTypes.R")
dashboardPage(header, sidebar, body)